---
commitizen:
  changelog_file: CHANGELOG.md
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.13.1
  version_files:
  - version.go
  version_scheme: semver
