---
commitizen:
  changelog_file: CHANGELOG.md
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.14.13
  version_files:
  - internal/version/version.go
  version_scheme: semver
