# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go install github.com/valyala/quicktemplate/qtc@latest
    - go generate ./...

builds:
  -
    main: ./cmd/postcards
    id: postcards
    binary: postcards
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - wasip1
    goarch:
      - amd64
      - arm64
      - wasm
    ldflags:
      - -s -w -X "main.Date={{.CommitDate}}"
  -
    main: ./cmd/postoffice-serviceworker
    id: postoffice-serviceworker
    binary: postoffice-serviceworker
    tool: tinygo
    flags:
      - -no-debug
    env:
      - CGO_ENABLED=0
    goos:
      - js
    goarch:
      - wasm
    ldflags:
      - ""
  # It's important the postoffice native binary is built after the WASM blob
  # As the WASM blob is baked into this server as part of an embed directive.
  # This needs to be done by calling goreleaser twice, specifying IDs to build.
  -
    main: ./cmd/postoffice
    id: postoffice
    binary: postoffice
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - wasip1
    goarch:
      - amd64
      - arm64
      - wasm
    ldflags:
      - -s -w -X "main.Date={{.CommitDate}}"

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    allow_different_binary_count: true

changelog:
  sort: asc
  groups:
  - title: ⚠️ Breaking changes
    regexp: "BREAKING CHANGE"
    order: 0
  - title: 👀 New features
    regexp: "^feat[(\\w)]*:+.*$"
    order: 1
  - title: 🐛 Bug fixes
    regexp: "^fix[(\\w)]*:+.*$"
    order: 2
  - title: Others
    order: 999
  filters:
    exclude:
    - '^docs[(\\w)]*:'
    - '^style[(\\w)]*:'
    - '^refactor[(\\w)]*:'
    - '^test[(\\w)]*:'
    - '^ci[(\\w)]*:'
    - '^chore[(\\w)]*:'
    - '^revert:'
    - '^bump:'
release:
  prerelease: auto
  draft: false
homebrew_casks:
- name: postcards
  repository:
    owner: jphastings
    name: homebrew-tools
    token: "{{ .Env.GITHUB_TOKEN }}"
  homepage: "https://dotpostcard.org/cli/postcards"
  url:
    verified: github.com/jphastings/dotpostcard
  description: "Tool for creating digital versions of physical postcards"
  license: "MIT"
